version: '3.1'

services:
  mongo:
    image: mongo:4.2.21
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./db-data:/data/db
      - ./dumps:/dumps
    ports:
      - "27017:27017"
